### ISSUE TITLE
Use Git tags to create release versions

### ISSUE THREAD

**Issue by mattmcadoo** [FearlessNite345/FS25_Liquid_Lime#10]
Could use Git tags that correspond with the versions sent to Giant's Modhub?  You mentioned that there's an update in testing with them and it would seem that it will include the production point for making liquid lime.  This would help in testing things out and add release notifications for the repo.

Info about Git tags and Github making releases available for download:  https://docs.github.com/en/repositories/releasing-projects-on-github/about-releases

**Comment by FearlessNite345** [comment]
i can once v1.1.0.0 is out they sent it back with some issues they had and im trying to find a fix before i send it back
