### ISSUE TITLE
Initial Thoughts and a Wish 

### ISSUE THREAD

**Issue by AlphaJr911** [FearlessNite345/FS25_Liquid_Lime#11]
Hi there, 

First off, I really appreciate the time you've put into this mod. I really like having an alternative method to apply lime on my farm, especially because Giants only gave us one implement to use in the base game. I enjoy using a standalone sprayer to apply the lime, as it makes it much quicker. 

My only wish is that you make it helper buyable so I do not have to refill the tank as helpers are applying it. I typically like a set it and forget it option, having the hired help apply it while I am off doing something else and come back to the field with it done. 

Thank you.

**Comment by FearlessNite345** [comment]
Glad you enjoy the mod this is a issue I am aware of and am struggling to find a solution (if there is one) as I don't have a ton of knowledge in the ins and outs of Farm sim but I do have v1.1.0.0 coming soon that brings some QoL changes and a new production the issues I have will be held back until a later update to give time to properly work out a fix
