### ISSUE TITLE
dds file error

### ISSUE THREAD

**Issue by criss20ster** [FearlessNite345/FS25_Liquid_Lime#3]
Warning: 'H:/ModyFS25/FS25_Liquid_Lime/brand/brand_TRUEEDGE.dds' (BC7) has undefined channel count, assuming 3 channels.

**Comment by FearlessNite345** [comment]
Appreciate the report I must have missed that in the log I will get to fixing this

**Comment by FearlessNite345** [comment]
Fixed in release v1.2.4.0
