### ISSUE TITLE
Usage request

### ISSUE THREAD

**Issue by MPNator** [FearlessNite345/FS25_Liquid_Lime#4]
Hello Joshua,
My name is Mathias, and i'm with a german modding-team for FarmingSimulator 22 / 25.

we found your mod an we are really interested in your script.
I would like to kindly ask you, if its possible to use your script for our needs. In this case we need your permission to change some things.

We won't upload the mod to FS25 Modhub - The only upload with occour on our own FS-Modding webpage - https://hot-hq.de/ - for our own users.

We will - of cource - mention you with our own version of this mod.

Unfortunately i can´t give you more information about our idea.

if you like - you can join our discord https://discord.gg/ZSK476vAd5

Best wishes.

Mathias / [HoT] MPNator

**Comment by FearlessNite345** [comment]
Not interested

**Comment by FearlessNite345** [comment]
Without knowing the use I'm not willing to allow free use of it
