### ISSUE TITLE
Kalk Production ?

### ISSUE THREAD

**Issue by Trunks19814** [FearlessNite345/FS25_Liquid_Lime#5]
Hey everyone, I think the idea is good, will there also be production for the liquid lime ?

and thx for the mod

**Comment by FearlessNite345** [comment]
Yes Liquid Lime Production is in the works any feedback on how you would like to do it would be greatly appreciated

**Comment by Trunks19814** [comment]
kalk + Water + (low) Silage additives ?

**Comment by FearlessNite345** [comment]
The Kalk assuming you mean base game lime is already considered as a option I'm currently planning for 2 ways to make liquid lime and planning it to not be insanely overpowered but still useful could be cheaper than buying

**Comment by Trunks19814** [comment]
yes, I meant the reason lime. and stones from the field as an option? stones to lime.

**Comment by FearlessNite345** [comment]
All options are being considered for version 1.1.0.0 which will be a few weeks out as per ModHub guidelines

**Comment by FearlessNite345** [comment]
Coming in v1.1.0.0 soon
