### ISSUE TITLE
Issue with Automatic Refueling workers

### ISSUE THREAD

**Issue by gbo35** [FearlessNite345/FS25_Liquid_Lime#6]
Thank you for the mod. I am encountering an issue when using it with workers. There is no automatic refueling like there is for solid lime, fertilizer, and herbicide. The sprayer empties the tank, but then it turns into a fertilizer source even though the tank is empty.

**Comment by FearlessNite345** [comment]
Interesting I will look into this ASAP and try getting it fixed in v1.1.0.0 which should be in a week or so give or take any delays with issues

**Comment by FearlessNite345** [comment]
So the worker just doesn't buy it right

**Comment by gbo35** [comment]
Yes, although in the options all resources for workers are available for purchase, this is not the case for liquid lime.

**Comment by FearlessNite345** [comment]
Interesting. I'm currently investigating ways to possibly fix this if it is even possible. In the meantime, please don't use helpers to avoid any issues. I do apologize for the inconvenience. I've so far not been able to find a way to fix this, seeing as I don’t know if there's a way to add it as a setting in the way helpers would see it anyway.

**Comment by FearlessNite345** [comment]
Closing this for now as currently i am unable to find a way to fix this but still investigating it thank you again for reporting this
