### ISSUE TITLE
How to add LiquidLime to trailer

### ISSUE THREAD

**Issue by Elwowood** [FearlessNite345/FS25_Liquid_Lime#7]
Hello,

Can i ask how i can add LiquidLime to a trailer.
I have modded the Abi Trailers from the game and have added Herbicide and Milk and other Basegame liquids without a problem.
But i cant figure out how to add LiquidLime.

Kind Regards,
Elwowood

**Comment by FearlessNite345** [comment]
Hello so if it's not supported based on fillTypeCategory you can add it to the trailer by editing the Trailer XML and adding LIQUIDLIME to the fillUnit fillTypes section

**Comment by Elwowood** [comment]
So im sorry for my Infinite Stupidity. 

I couldnt figure out why it wouldnt work because it worked for everything else.
Turns out im more stupid than i thought.
While testing mods i usually only select that mod. now while testing a mod that uses another mod for example LiquidLime it might be smart to select that one too before testing.
Thats what i did wrong. i forgot to activate the liquidlime mod while testing.
Thanks for the answer and sorry for the inconvinience.

Love the mod BTW.

**Comment by FearlessNite345** [comment]
Ah ok glad you got it working FYI in v1.1.0.0 i have included the chrome trailers with Liquid Lime supported
