### ISSUE TITLE
Surggestion for liquid lime.

### ISSUE THREAD

**Issue by Cryofrost-91** [FearlessNite345/FS25_Liquid_Lime#8]
Hey, i really love your mod, its such a cool way to get extra utility out of your sprayers all while its still realistic. 
though I noticed that in FS25 by default you can have Liquid Fert and Herbicide in various towed barrels. it would be really cool, and very useful to be able to also carry liquid lime in these, included in the mod. gives you more options to overcome the lower capacity of sprayers versus the Bredal spreader.

**Comment by FearlessNite345** [comment]
Hello so are you meaning like the pull behind water type trailers? Like the white one

**Comment by Cryofrost-91** [comment]
yeah, the Lizard MKS 8 and Lizard MKS 32, so the chrome towed barrels, can carry Liquid Fertiliser and Herbicide by default.

the use case being, the amazone sprayer has a trailer hook, so you can vastly increase its liquid capacity. and also its just an easier way to transport large amounts of Lime to a remote field, if you use a different sprayer.
