### ISSUE TITLE
Liquid Lime production

### ISSUE THREAD

**Issue by wijba** [FearlessNite345/FS25_Liquid_Lime#9]
Very lovely mod.

Is it possible to create a liquid lime production station, to create your own liquid lime. For example with lime and water, or with rocks which will be crushed first and water? 

And then with an output  to IBC tanks or tanker trailer like Abi.

TX

**Comment by wijba** [comment]
Hi, I downloaded 1.2.4.0 but I can't find the Liquid Lime Production ingame?

**Comment by FearlessNite345** [comment]
@wijba it is not out yet as 1.2.4.0 is the 1.0.0.0 version on the modhub i had to remove the other versions to get it into the modhub it is pending testing on giants so please just wait for 1.1.0.0 on the modhub sorry for the confusion i will remove the github releases to clear up any confusion

**Comment by FearlessNite345** [comment]
![image](https://github.com/user-attachments/assets/6081bdaf-8077-4c74-9926-d5cdddbf9196)

**Comment by wijba** [comment]
TX for that, I downloaded the ZIP from the Code tap. and there it is i, so I use that one. Is it possible to make a sprout on it with a filltrigger for liquid trailers.

**Comment by FearlessNite345** [comment]
The trigger point should work with trailers for the water

**Comment by FearlessNite345** [comment]
Unless you mean unloading the liquid lime to a trailer instead of pallets
